# Generated by Django 5.0.1 on 2024-01-18 04:56

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_image_about_us_alter_homepage_subtitle'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('figcaptionblock', wagtail.blocks.StructBlock([('caption', wagtail.blocks.CharBlock()), ('figure', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image_about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Картинка для первого блока О НАС'),
        ),
    ]
