# Generated by Django 5.0.1 on 2024-01-18 08:39

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('figcaptionblock', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('date', wagtail.blocks.CharBlock()), ('short_title', wagtail.blocks.CharBlock()), ('type_work', wagtail.blocks.CharBlock()), ('message', wagtail.blocks.CharBlock(max_length=1000)), ('requirements', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock())), ('caption', wagtail.blocks.CharBlock()), ('figure', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, use_json_field=True),
        ),
    ]
