# Generated by Django 5.0.1 on 2024-01-18 09:48

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('work_card', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, null=True, verbose_name='Заголовок должности в модальном окне')), ('date', wagtail.blocks.CharBlock(blank=True, null=True, verbose_name='Дата')), ('short_title', wagtail.blocks.CharBlock(blank=True, null=True, verbose_name='Заголовок должности в модальном окне')), ('type_work', wagtail.blocks.CharBlock(blank=True, null=True, verbose_name='Заголовок должности в модальном окне')), ('message', wagtail.blocks.CharBlock(blank=True, max_length=1000, null=True, verbose_name='Заголовок должности в модальном окне')), ('requirements', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(), verbose_name='Список требований'))]))], blank=True, use_json_field=True, verbose_name='Блоки с карточкой работы'),
        ),
    ]
