# Generated by Django 5.0.1 on 2024-01-18 13:43

import wagtail.fields
import wagtailvideos.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_body2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body3',
            field=wagtail.fields.StreamField([('video', wagtailvideos.blocks.VideoChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
