# Generated by Django 5.0.1 on 2024-01-18 14:04

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailvideos.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homepage_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body2',
            field=wagtail.fields.StreamField([('gallery_card', wagtail.blocks.StructBlock([('video_gallery', wagtailvideos.blocks.VideoChooserBlock(label='Видеофайл для блока свайпера', required=False)), ('image_gallery', wagtail.images.blocks.ImageChooserBlock(label='Картинка для блока свайпера', required=False)), ('video_url', wagtail.embeds.blocks.EmbedBlock(label='URL видео', required=False))], blank=True, null=True, use_json_field=True, verbose_name='Блоки картинок / видео на главной странице свайпера'))], blank=True, use_json_field=True),
        ),
    ]
