# Generated by Django 5.0.1 on 2024-01-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homepage_intro_about_us_homepage_intro_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='rtf_intro_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст/Контент подзаголовка'),
        ),
    ]
