# Generated by Django 5.0.1 on 2024-01-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_homepage_rtf_intro_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='rtf_intro_subtitle',
            new_name='intro_subtitle',
        ),
    ]
