# Generated by Django 5.0.1 on 2024-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_rtf_intro_subtitle_homepage_intro_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='intro_about_us',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
    ]
