# Generated by Django 5.0.1 on 2024-01-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_homepage_intro_about_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='rtf_intro_about_us',
            new_name='intro_about_us_subtitle',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст/Контент подзаголовка'),
        ),
    ]
