# Generated by Django 5.0.1 on 2024-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_rtf_intro_about_us_homepage_intro_about_us_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='intro_about_us_subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст/Контент подзаголовка'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок. Блок после слайдера'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подзаголовок'),
        ),
    ]
