# Generated by Django 5.0.1 on 2024-01-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_homepage_intro_about_us_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='browl_royale_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст в блоке Browl Royale'),
        ),
    ]
