# Generated by Django 5.0.1 on 2024-01-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_homepage_browl_royale_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='browl_royale_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='browl_royale_text1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст в блоке Browl Royale 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='browl_royale_text2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст в блоке Browl Royale 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='browl_royale_text3',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст в блоке Browl Royale 3'),
        ),
    ]
