# Generated by Django 5.0.1 on 2024-01-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_homepage_browl_royale_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='our_projects_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок. Наши проекты'),
        ),
    ]
