# Generated by Django 5.0.1 on 2024-01-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homepage_our_projects_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='our_projects_text',
            new_name='our_projects_title',
        ),
    ]
