# Generated by Django 5.0.1 on 2024-01-19 10:14

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_our_projects_text_homepage_our_projects_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_service',
            field=wagtail.fields.StreamField([('service_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, label='Заголовок должности в модальном окне', null=True)), ('date', wagtail.blocks.CharBlock(blank=True, label='Дата', null=True)), ('short_title', wagtail.blocks.CharBlock(blank=True, label='Название должности в карточке', null=True)), ('type_work', wagtail.blocks.CharBlock(blank=True, label='Тип работы (Удаленно / и другие)', null=True)), ('message', wagtail.blocks.CharBlock(blank=True, label='Описание работы ', max_length=1000, null=True)), ('requirements', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(), label='Список требований'))], blank=True, verbose_name='Блоки картинками партнеров на главной странице'))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок. Услуги'),
        ),
    ]
