# Generated by Django 5.0.1 on 2024-01-19 10:18

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailvideos.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_homepage_body_service_homepage_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body2',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_gallery',
            field=wagtail.fields.StreamField([('gallery_card', wagtail.blocks.StructBlock([('video_gallery', wagtailvideos.blocks.VideoChooserBlock(label='Видеофайл для блока свайпера', required=False)), ('image_gallery', wagtail.images.blocks.ImageChooserBlock(label='Картинка для блока свайпера', required=False)), ('video_url', wagtail.embeds.blocks.EmbedBlock(label='URL видео', required=False))], blank=True, label='Блоки картинок / видео на главной странице свайпера', null=True))], blank=True, use_json_field=True, verbose_name='Блок настройки картинок / видео для свайпера'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_work',
            field=wagtail.fields.StreamField([('work_card', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, label='Заголовок должности в модальном окне', null=True)), ('date', wagtail.blocks.CharBlock(blank=True, label='Дата', null=True)), ('short_title', wagtail.blocks.CharBlock(blank=True, label='Название должности в карточке', null=True)), ('type_work', wagtail.blocks.CharBlock(blank=True, label='Тип работы (Удаленно / и другие)', null=True)), ('message', wagtail.blocks.CharBlock(blank=True, label='Описание работы ', max_length=1000, null=True)), ('requirements', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(), label='Список требований'))], blank=True, verbose_name='Блоки с карточкой работы на главной странице'))], blank=True, use_json_field=True, verbose_name='Блок настройки карточек с работой'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_service',
            field=wagtail.fields.StreamField([('service_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, label='Заголовок должности в модальном окне', null=True)), ('date', wagtail.blocks.CharBlock(blank=True, label='Дата', null=True)), ('short_title', wagtail.blocks.CharBlock(blank=True, label='Название должности в карточке', null=True)), ('type_work', wagtail.blocks.CharBlock(blank=True, label='Тип работы (Удаленно / и другие)', null=True)), ('message', wagtail.blocks.CharBlock(blank=True, label='Описание работы ', max_length=1000, null=True)), ('requirements', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(), label='Список требований'))], blank=True, verbose_name='Блоки картинками партнеров на главной странице'))], blank=True, use_json_field=True, verbose_name='Блок услуг на главной'),
        ),
    ]
