# Generated by Django 5.0.1 on 2024-01-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_footer'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='bodytext',
        ),
        migrations.AddField(
            model_name='footer',
            name='accept_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст принятия политики'),
        ),
        migrations.AddField(
            model_name='footer',
            name='conditions_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на условия'),
        ),
        migrations.AddField(
            model_name='footer',
            name='conditions_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Условия оказания услуг текст'),
        ),
        migrations.AddField(
            model_name='footer',
            name='image_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Картинка в футере слева'),
        ),
        migrations.AddField(
            model_name='footer',
            name='policy_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на политику конфиденциальности'),
        ),
        migrations.AddField(
            model_name='footer',
            name='policy_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Политика конфиденциальности текст'),
        ),
        migrations.AddField(
            model_name='footer',
            name='text_footer_bottom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст про политику конфиденциальности внизу футера'),
        ),
        migrations.AddField(
            model_name='footer',
            name='year_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Года работы компании в футере'),
        ),
    ]
