# Generated by Django 5.0.1 on 2024-02-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_laptopmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopmenu',
            name='link_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='5 Ссылка'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='link_facility',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='4 Ссылка'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='link_main',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на главную'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='link_protfolio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2 Ссылка'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='link_work',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3 Ссылка'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='mail_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email ссылка формата mailto:m.zhvikovm@gmail.com'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='telephone_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон ссылка формата tel:79028607651'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='title_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок 5 ссылки'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='title_facility',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок 4 ссылки'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='title_portfolio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок 2 ссылки'),
        ),
        migrations.AddField(
            model_name='laptopmenu',
            name='title_work',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок 3 ссылки'),
        ),
    ]
