# Generated by Django 5.0.1 on 2024-02-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_laptopmenu_link_contact_laptopmenu_link_facility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок главной ссылки')),
                ('link_main', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на главную')),
                ('title_portfolio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок 2 ссылки')),
                ('link_protfolio', models.CharField(blank=True, max_length=100, null=True, verbose_name='2 Ссылка')),
                ('title_work', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок 3 ссылки')),
                ('link_work', models.CharField(blank=True, max_length=100, null=True, verbose_name='3 Ссылка')),
                ('title_facility', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок 4 ссылки')),
                ('link_facility', models.CharField(blank=True, max_length=100, null=True, verbose_name='4 Ссылка')),
                ('title_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок 5 ссылки')),
                ('link_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='5 Ссылка')),
            ],
            options={
                'verbose_name': 'Хедер',
                'verbose_name_plural': 'Хедеры',
            },
        ),
    ]
