# Generated by Django 5.0.1 on 2024-02-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_header_image_carrier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='link_protfolio',
            new_name='link_portfolio',
        ),
    ]
