# Generated by Django 5.0.1 on 2024-02-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_workpage_get_contact_title_workpage_image_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpage',
            name='get_contact_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Короткий текст перед кнопкой зеленый'),
        ),
    ]
