# Generated by Django 5.0.1 on 2024-04-24 17:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policypage',
            name='title2',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='title1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='текст заголовка'),
        ),
    ]
