# Generated by Django 5.0.1 on 2024-02-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.CharField(blank=True, max_length=150, null=True)),
                ('image_logo', models.ImageField(upload_to='images/')),
                ('image_one', models.ImageField(upload_to='images/')),
                ('image_two', models.ImageField(upload_to='images/')),
                ('image_three', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
