# Generated by Django 5.0.1 on 2024-04-24 17:42

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourstudia', '0003_studiapage_image_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiapage',
            name='body_advantage',
            field=wagtail.fields.StreamField([('advantage_section', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Картинка для блока преимуществ', required=False)), ('title', wagtail.blocks.CharBlock(blank=True, label='Заголовок белый текст', null=True)), ('title2', wagtail.blocks.CharBlock(blank=True, label='Заголовок зеленый текст', null=True)), ('subtitle', wagtail.blocks.CharBlock(blank=True, label='Текст', null=True))], blank=True, verbose_name='Блоки c преимуществами работы'))], blank=True, use_json_field=True, verbose_name='Блоки c преимуществами работы'),
        ),
    ]
