# Generated by Django 5.0.1 on 2024-02-19 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitypage',
            name='name_owner',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст имя основателя'),
        ),
        migrations.AddField(
            model_name='facilitypage',
            name='subtitle_name_owner',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст под именем основателя'),
        ),
        migrations.AlterField(
            model_name='facilitypage',
            name='image_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Картинка основателя'),
        ),
    ]
