# Generated by Django 5.0.1 on 2024-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourcontacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='title1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
    ]
