# Generated by Django 5.0.1 on 2024-02-12 12:02

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Белый текст заголовка')),
                ('title2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Зеленый текст заголовка')),
                ('subtitle', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подзаголовок')),
                ('body_advantage', wagtail.fields.StreamField([('advantage_section', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Картинка для блока преимуществ', required=False)), ('title', wagtail.blocks.CharBlock(blank=True, label='Заголовок белый текст', null=True)), ('title2', wagtail.blocks.CharBlock(blank=True, label='Заголовок зеленый текст', null=True)), ('subtitle', wagtail.blocks.CharBlock(blank=True, label='Текст', null=True))], blank=True, verbose_name='Блоки c преимуществами  работы'))], blank=True, use_json_field=True, verbose_name='Блок услуг на главной')),
                ('body_work', wagtail.fields.StreamField([('advantage_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, label='Заголовок должности в модальном окне', null=True)), ('date', wagtail.blocks.CharBlock(blank=True, label='Дата', null=True)), ('short_title', wagtail.blocks.CharBlock(blank=True, label='Название должности в карточке', null=True)), ('type_work', wagtail.blocks.CharBlock(blank=True, label='Тип работы (Удаленно / и другие)', null=True)), ('message', wagtail.blocks.CharBlock(blank=True, label='Описание работы ', max_length=1000, null=True)), ('requirements', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(), label='Список требований'))], blank=True, verbose_name='Блоки c картинками партнеров на главной странице'))], blank=True, use_json_field=True, verbose_name='Блок услуг на главной')),
                ('image_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Картинка первого блока')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
