# Generated by Django 5.0.1 on 2024-02-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpage',
            name='get_contact_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Короткий текст перед кнопкой'),
        ),
        migrations.AddField(
            model_name='workpage',
            name='image_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Картинка для блока контактов'),
        ),
        migrations.AddField(
            model_name='workpage',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='workpage',
            name='text2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='текст 2'),
        ),
        migrations.AddField(
            model_name='workpage',
            name='text_btn',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='текст кнопки'),
        ),
        migrations.AddField(
            model_name='workpage',
            name='vacancy_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Длинный текст перед кнопкой'),
        ),
    ]
